language: node_js

node_js:
  - '12'

services:
  - mongodb
  - redis

cache:
  directories:
    - node_modules

install:
  - npm ci

before_script:
  - sleep 15

script:
  - npm test

before_deploy:
  - export ELASTIC_BEANSTALK_LABEL=nodejs-auth-app_$(git log -1 --format="%ci")

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: us-east-2
  app: nodejs-auth
  env: nodejs-auth-dev
  on:
    repo: baturtulek/nodejs-auth-private
  bucket: elasticbeanstalk-us-east-2-937588586165