version: '2.4'

services:
  authentication-api:
    build:
      context: ./
    networks:
      - authentication-network
    environment:
      - NODE_ENV=production
      - PORT=8080
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - MONGODB_URI=mongodb://database:27017/authDb
    ports:
      - '8080:8080'
  redis:
    image: "redis:alpine"
    networks:
      - authentication-network
    ports:
      - '6379:6379'
  database:
    image: "mongo"
    networks:
      - authentication-network
    volumes:
      - ./mongo-volume:/data/db 
    ports:
      - '27017:27017'
      
networks:
  authentication-network:
    driver: bridge