Transform: 'AWS::Serverless-2016-10-31'
Resources:
  nodejsAuthentication:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: src/serverless.handler
      Timeout: 10
      MemorySize: 256
      Events:
        AuthLogin:
          Type: Api
          Properties:
            Path: /v1/auth/login
            Method: post
        AuthLogout:
          Type: Api
          Properties:
            Path: /v1/auth/logout
            Method: post
        AuthRegister:
          Type: Api
          Properties:
            Path: /v1/auth/register
            Method: post
        AuthProfile:
          Type: Api
          Properties:
            Path: /v1/auth/profile
            Method: get
      Environment:
        Variables:
          NODE_ENV: lambda
          REDIS_PORT: 6379
          REDIS_HOST: 127.0.0.1
          MONGODB_URI: mongodb://127.0.0.1:27017/authDb

